name: SSH Auto Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: yarn config set registry https://registry.npm.taobao.org && yarn

      - name: Build
        run: yarn build

      - name: Deploy to Server
        uses: hengkx/ssh-deploy@v1.0.1
        with:
          USERNAME: ${{ secrets.DEPLOY_USER }}
          PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          HOST: ${{ secrets.REMOTE_HOST }}
          SOURCE: 'dist'
          TARGET: ${{secrets.REMOTE_TARGET}}
          # AFTER_COMMAND: 'npm run stop && npm install --production && npm run start'
